### PR TITLE
 Improved Update() by utilizing newer EF5+'s features & obeying open/closed principle by providing IQueryable instead of ICollection

### PR DESCRIPTION
**Pull request by Eagle3386**

### CODE REVIEW

**Comment by Eagle3386** [comment]
@mombrea, it's been a while since you requested a fixed PR and I provided it.
Is there anything I can/need to improve further in order to get this merged? :)

**Comment by mombrea** [comment]
Wow, yes it has been a long time! Sorry about that.

I agree with your changes for the Get and Find methods, but why remove the Async versions of Add, Update, Delete, and Count?

**Comment by Eagle3386** [comment]
Sorry for me being late this time, but I couldn't reply sooner.

Regarding your question: as the MSDN [states](https://msdn.microsoft.com/en-us/library/jj819165.aspx) that async EF is done by using `async` and `await`, there's no real asynchronous operation. Sure, it prevents blocking the current thread. But other than that, there's no benefit, because EF itself isn't even capable of doing asynchronous queries due to its desire to ensure database consistency - otherwise, you would be able to modify entities which others are possibly reading or even modifying at the same time.

Hence my suggestion to drop this, because your repository is entitled as being **generic**. If one really needs the query thread to be non-blocked, then s/he can inherit the generic interface and do it on her/his own. 😃

**Comment by mombrea** [comment]
Prevention of blocking the current thread is the purpose of async. True the EF query won't be async, but the query takes time - and during that time the .NET code can be free to continue processing requests while the EF query is running. 

I'd prefer to keep the Async methods for Add, Update, Delete, and Count. They don't have to be used but it's convenient to have the option in the generic.

**Comment by Eagle3386** [comment]
My recent commit just updated my name, but to reply to your comment: I explicitly checked `Allow edits from maintainers`, because of my atomic commits. This way, you can leverage from my implemented improvements while leaving out the `async` removals by cherry-picking (i. e. unchecking 79765cc upon your merge of my PR).

**Comment by Eagle3386** [comment]
My recent commit just updated my name, but to reply to your comment: I explicitly checked `Allow edits from maintainers`, because of my atomic commits. This way, you can leverage from my implemented improvements while leaving out the `async` removals by cherry-picking (i. e. unchecking 79765cc upon your merge of my PR).

Looking forward to your merge, so that I can close & delete this patch-branch afterwards as it's been around almost 2 years now.. :wink:

**Comment by Eagle3386** [comment]
@mombrea Please delete this PR of mine as I seem to be disallowed to do so myself.
As a friendly suggestion: doing a (generic) repository atop EF is just wrong as it "over-engineers" the fact that EF itself is already the repository to be consumed/used.

**Pull request closed without merging**
